### ISSUE TITLE
Consider making this private?

### ISSUE THREAD

**Issue by bazwilliams** [kylegordon/cv#1]

**Comment by kylegordon** [comment]
ta, but meh it's public anyway at https://lodge.glasgownet.com/about/cv/ :-)

My CV is all written in LaTeX and I want to generate the PS, PDF and HTML via Travis now, rather than locally.

**Comment by bazwilliams** [comment]
Oooh - you could use a multi stage build to compile the LaTeX using `blang/latex-docker` and copy the artefacts into an nginx container...
